# -*- coding: utf-8 -*-
"""
Run by Claude Code at the start of a session (SessionStart hook); what it
prints goes into Claude's context. Generated by MS43 AI-Tuner.

Checks: is the MS43 AI-Tuner window (the MCP server) open; were generated
files changed by hand; are there log files lying in the project folder that
were not added on the Logs screen.
"""

import hashlib
import json
import os
import socket
import sys
from urllib.parse import urlparse

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ALWAYS = (".claude/ms43-rules.md", ".mcp.json", ".claude/settings.json")


def main() -> int:
    out = []
    try:
        with open(os.path.join(ROOT, ".mcp.json"), encoding="utf-8") as fh:
            servers = json.load(fh).get("mcpServers", {})
    except (OSError, ValueError):
        servers = {}
    for name, cfg in servers.items():
        url = urlparse(cfg.get("url") or (cfg.get("env") or {}).get("MS43_URL", ""))
        try:
            with socket.create_connection((url.hostname or "127.0.0.1", url.port or 80), timeout=1):
                pass
        except OSError:
            bridged = cfg.get("type") == "stdio"
            out.append(f"MS43 AI-Tuner window is CLOSED (MCP server '{name}' at {url.netloc} does "
                       "not answer). Ask the owner to open it before using the ms43 tools."
                       + (" Once it is open the tools work at once, no reconnect is needed."
                          if bridged else " Then the owner reconnects it: /mcp -> Reconnect."))
    try:
        with open(os.path.join(ROOT, ".ms43project.json"), encoding="utf-8") as fh:
            hashes = json.load(fh).get("files", {})
    except (OSError, ValueError):
        hashes = {}
    changed = []
    for rel, sha in hashes.items():
        if rel in ALWAYS:
            continue
        path = os.path.join(ROOT, *rel.split("/"))
        try:
            with open(path, "rb") as fh:
                if hashlib.sha256(fh.read()).hexdigest() != sha:
                    changed.append(rel)
        except OSError:
            changed.append(rel + " (missing)")
    if changed:
        out.append("Generated files changed by hand (the program will not overwrite them, so they "
                   "may be outdated): " + ", ".join(changed))
    loose = [f for f in os.listdir(ROOT) if f.lower().endswith((".xdl", ".csv"))]
    if loose:
        out.append("Log files lying in the project folder, not added on the Logs screen: "
                   + ", ".join(sorted(loose)[:20]))
    if os.path.isfile(os.path.join(ROOT, "analysis", "STATE.md")):
        out.append("Read analysis/STATE.md (the current state of the car) before anything else.")
    if out:
        print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
