# -*- coding: utf-8 -*-
"""
The link between Claude Code and the MS43 AI-Tuner window. Generated by MS43 AI-Tuner.

Claude Code starts this script itself (a stdio MCP server in .mcp.json), so the
"ms43" server never ends up "failed" when the window was closed at the start of
a session. Every request is passed to the window's live server over HTTP:

- the window is open: the window answers;
- the window is closed: the tool list comes from the copy saved next to this
  script, and a tool call answers that the window is closed. As soon as the
  owner opens the window, the next call works - no reconnect needed.

Settings come from the environment (.mcp.json): MS43_URL, MS43_TOKEN.
Only the Python standard library is used.
"""

import json
import os
import sys
import urllib.error
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, "ms43-tools.json")
URL = os.environ.get("MS43_URL", "http://127.0.0.1:8743/mcp")
TOKEN = os.environ.get("MS43_TOKEN", "")
CLOSED = ("The MS43 AI-Tuner window is closed (its server at {url} does not answer). Ask the "
          "owner to open the window, then call the tool again - no reconnect is needed.")


class WindowClosed(Exception):
    pass


def forward(message):
    """One JSON-RPC message to the window; its answer (None for a notification)."""
    req = urllib.request.Request(
        URL, data=json.dumps(message).encode("utf-8"), method="POST",
        headers={"Content-Type": "application/json", "Authorization": "Bearer " + TOKEN,
                 "Accept": "application/json, text/event-stream"})
    try:
        with urllib.request.urlopen(req, timeout=300) as res:
            text = res.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        if exc.code == 401:
            raise RuntimeError("The window refused the token: press \"Update the project\" in the "
                               "window (AI assistant screen) and start a new session.") from exc
        raise RuntimeError(f"The window answered HTTP {exc.code}.") from exc
    except (urllib.error.URLError, OSError) as exc:
        raise WindowClosed(str(exc)) from exc
    return json.loads(text) if text.strip() else None


def cached_tools():
    try:
        with open(CACHE, encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return []


def save_tools(tools):
    try:
        tmp = CACHE + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            json.dump(tools, fh, ensure_ascii=False)
        os.replace(tmp, CACHE)
    except OSError:
        pass


def answer(message):
    method = message.get("method")
    rid = message.get("id")
    if method == "initialize":
        # answered here, so the session starts whether the window is open or not
        params = message.get("params") or {}
        return {"jsonrpc": "2.0", "id": rid, "result": {
            "protocolVersion": params.get("protocolVersion") or "2024-11-05",
            "capabilities": {"tools": {"listChanged": False}},
            "serverInfo": {"name": "ms43-bridge", "version": "1"}}}
    if rid is None:                                   # a notification
        try:
            forward(message)
        except Exception:  # noqa: BLE001 - nothing to answer
            pass
        return None
    if method == "ping":
        return {"jsonrpc": "2.0", "id": rid, "result": {}}
    try:
        reply = forward(message)
    except WindowClosed:
        if method == "tools/list":
            return {"jsonrpc": "2.0", "id": rid, "result": {"tools": cached_tools()}}
        if method == "tools/call":
            return {"jsonrpc": "2.0", "id": rid, "result": {
                "content": [{"type": "text", "text": CLOSED.format(url=URL)}], "isError": True}}
        return {"jsonrpc": "2.0", "id": rid, "error": {"code": -32000, "message": CLOSED.format(url=URL)}}
    except Exception as exc:  # noqa: BLE001 - reported to Claude
        if method == "tools/call":
            return {"jsonrpc": "2.0", "id": rid, "result": {
                "content": [{"type": "text", "text": str(exc)}], "isError": True}}
        return {"jsonrpc": "2.0", "id": rid, "error": {"code": -32000, "message": str(exc)}}
    if method == "tools/list" and isinstance(reply, dict):
        tools = (reply.get("result") or {}).get("tools")
        if tools:
            save_tools(tools)
    return reply


def main():
    stdin = sys.stdin.buffer
    stdout = sys.stdout.buffer
    for raw in stdin:
        raw = raw.strip()
        if not raw:
            continue
        try:
            message = json.loads(raw.decode("utf-8"))
        except ValueError:
            out = {"jsonrpc": "2.0", "id": None, "error": {"code": -32700, "message": "parse error"}}
        else:
            if isinstance(message, list):
                out = [a for a in (answer(m) for m in message if isinstance(m, dict)) if a]
                out = out or None
            else:
                out = answer(message) if isinstance(message, dict) else None
        if out is not None:
            stdout.write(json.dumps(out, ensure_ascii=False).encode("utf-8") + b"\n")
            stdout.flush()
    return 0


if __name__ == "__main__":
    sys.exit(main())
